version: '3.4'

services:

  # Mongo database
  # Runs on port 27017
  # Restart on failures
  # Connect via URL 'mongo:27017'
  mongo:
    restart: on-failure
    image: mongo
    container_name: mongo
    command: "--smallfiles --logpath=/dev/null"
    env_file:
      - mongo.env

  api:
    restart: on-failure
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    env_file:
      - api.env
    depends_on:
      - mongo