version: '3.7'

services:

  # Accessible in IB.ai network on http://ibai_api:3000
  ibai_api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - ibai_redis

  # redis://ibai_redis:6379
  ibai_redis:
    image: redis
