version: '2.0'

services:

  # Accessible in IB.ai network on http://api:8080
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    depends_on:
      - db

  # Publicly accessible on http://<host>/
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - "9010:9010"
    depends_on:
      - api

  # redis://db:6379
  db:
    image: redis

# Connecting to bot's network.
# The IB.ai docker-compose must be started first.
#networks:
#  ibai_main:
#    external: true
