version: '3.7'

services:

  # Accessible in IB.ai network on http://ibai_web:3000
  ibai_web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - ibai_redis

  redis-commander:
      image: rediscommander/redis-commander:latest
      environment:
       - REDIS_HOSTS=local:ibai_redis:6379
      ports:
       - "8081:8081"
      depends_on:
       - ibai_redis

  # redis://ibai_redis:6379
  ibai_redis:
    image: redis
